name: hipertensi_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter_svg: ^0.22.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

